version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: sentpazar-db
    environment:
      POSTGRES_DB: sentpazar
      POSTGRES_USER: sentpazar
      POSTGRES_PASSWORD: S3ntP@z2026!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sentpazar-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
