using Npgsql;

var conn = new NpgsqlConnection("Host=localhost;Port=5432;Database=sentpazar;Username=sentpazar;Password=S3ntP@z2026!");
await conn.OpenAsync();

// Reset schema
using var resetCmd = new NpgsqlCommand("DROP SCHEMA public CASCADE; CREATE SCHEMA public;", conn);
await resetCmd.ExecuteNonQueryAsync();
Console.WriteLine("Schema reset!");
var sql = @"
-- AspNetRoles
CREATE TABLE ""AspNetRoles"" (
    ""Id"" TEXT NOT NULL,
    ""ConcurrencyStamp"" TEXT,
    ""Name"" TEXT,
    ""NormalizedName"" TEXT,
    CONSTRAINT ""PK_AspNetRoles"" PRIMARY KEY (""Id"")
);
CREATE UNIQUE INDEX ""RoleNameIndex"" ON ""AspNetRoles"" (""NormalizedName"");

-- AspNetUsers
CREATE TABLE ""AspNetUsers"" (
    ""Id"" TEXT NOT NULL,
    ""AccessFailedCount"" INTEGER NOT NULL,
    ""AddressLine"" TEXT,
    ""AvatarUrl"" TEXT,
    ""City"" TEXT,
    ""CompanyAddress"" TEXT,
    ""CompanyLogoUrl"" TEXT,
    ""CompanyMersisNumber"" TEXT,
    ""CompanyName"" TEXT,
    ""CompanyPhone"" TEXT,
    ""CompanyTaxNumber"" TEXT,
    ""CompanyTaxOffice"" TEXT,
    ""CompanyWebSite"" TEXT,
    ""ConcurrencyStamp"" TEXT,
    ""CorporateApprovalDate"" TEXT,
    ""CorporateNote"" TEXT,
    ""Email"" TEXT,
    ""EmailConfirmed"" BOOLEAN NOT NULL,
    ""EmailNotifications"" BOOLEAN NOT NULL,
    ""FcmToken"" TEXT,
    ""FcmTokenUpdatedAtUtc"" TEXT,
    ""FeaturedListingsIncluded"" INTEGER NOT NULL,
    ""FeaturedListingsUsed"" INTEGER NOT NULL,
    ""FullName"" TEXT NOT NULL,
    ""IsCorporateApproved"" BOOLEAN NOT NULL,
    ""IsCorporateMember"" BOOLEAN NOT NULL,
    ""IsSubscriptionActive"" BOOLEAN NOT NULL,
    ""IsVerifiedSeller"" BOOLEAN NOT NULL,
    ""ListingsRemainingThisMonth"" INTEGER NOT NULL,
    ""LockoutEnabled"" BOOLEAN NOT NULL,
    ""LockoutEnd"" TEXT,
    ""NormalizedEmail"" TEXT,
    ""NormalizedUserName"" TEXT,
    ""PasswordHash"" TEXT,
    ""PhoneNumber"" TEXT,
    ""PhoneNumberConfirmed"" BOOLEAN NOT NULL,
    ""SecurityStamp"" TEXT,
    ""SmsNotifications"" BOOLEAN NOT NULL,
    ""SubscriptionEndDate"" TEXT,
    ""SubscriptionPlan"" TEXT,
    ""SubscriptionStartDate"" TEXT,
    ""TotalListingsAllowed"" INTEGER NOT NULL,
    ""TwoFactorEnabled"" BOOLEAN NOT NULL,
    ""UserName"" TEXT,
    ""VerificationNotes"" TEXT,
    ""VerifiedAt"" TEXT,
    ""VerifiedByAdminId"" TEXT,
    ""VitrinListingsIncluded"" INTEGER NOT NULL,
    ""VitrinListingsUsed"" INTEGER NOT NULL,
    CONSTRAINT ""PK_AspNetUsers"" PRIMARY KEY (""Id"")
);
CREATE UNIQUE INDEX ""EmailIndex"" ON ""AspNetUsers"" (""NormalizedEmail"");
CREATE UNIQUE INDEX ""UserNameIndex"" ON ""AspNetUsers"" (""NormalizedUserName"");

-- AspNetUserClaims, AspNetUserLogins, AspNetUserRoles, AspNetUserTokens
CREATE TABLE ""AspNetUserClaims"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" TEXT NOT NULL,
    ""ClaimType"" TEXT,
    ""ClaimValue"" TEXT,
    CONSTRAINT ""PK_AspNetUserClaims"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""AspNetUserLogins"" (
    ""LoginProvider"" TEXT NOT NULL,
    ""ProviderKey"" TEXT NOT NULL,
    ""ProviderDisplayName"" TEXT,
    ""UserId"" TEXT NOT NULL,
    CONSTRAINT ""PK_AspNetUserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
    CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""AspNetUserRoles"" (
    ""UserId"" TEXT NOT NULL,
    ""RoleId"" TEXT NOT NULL,
    CONSTRAINT ""PK_AspNetUserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
    CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""AspNetUserTokens"" (
    ""UserId"" TEXT NOT NULL,
    ""LoginProvider"" TEXT NOT NULL,
    ""Name"" TEXT NOT NULL,
    ""Value"" TEXT,
    CONSTRAINT ""PK_AspNetUserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
    CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE INDEX ""IX_AspNetUserClaims_UserId"" ON ""AspNetUserClaims"" (""UserId"");
CREATE INDEX ""IX_AspNetUserLogins_UserId"" ON ""AspNetUserLogins"" (""UserId"");
CREATE INDEX ""IX_AspNetUserRoles_RoleId"" ON ""AspNetUserRoles"" (""RoleId"");

-- AspNetRoleClaims
CREATE TABLE ""AspNetRoleClaims"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""RoleId"" TEXT NOT NULL,
    ""ClaimType"" TEXT,
    ""ClaimValue"" TEXT,
    CONSTRAINT ""PK_AspNetRoleClaims"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE
);

-- Listings
CREATE TABLE ""Listings"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""FullName"" TEXT NOT NULL,
    ""Phone"" TEXT NOT NULL,
    ""AllowWhatsApp"" BOOLEAN NOT NULL,
    ""AllowMessages"" BOOLEAN NOT NULL,
    ""Title"" TEXT NOT NULL,
    ""Description"" TEXT NOT NULL,
    ""Tags"" TEXT,
    ""City"" TEXT NOT NULL,
    ""District"" TEXT NOT NULL,
    ""Neighborhood"" TEXT,
    ""Address"" TEXT,
    ""Latitude"" DOUBLE PRECISION,
    ""Longitude"" DOUBLE PRECISION,
    ""Category"" TEXT NOT NULL,
    ""SubCategory"" TEXT,
    ""Type"" TEXT NOT NULL,
    ""PriceAmount"" DECIMAL(18,2) NOT NULL,
    ""PriceCurrency"" TEXT NOT NULL,
    ""PriceType"" TEXT NOT NULL,
    ""PriceDescription"" TEXT,
    ""Negotiable"" BOOLEAN NOT NULL,
    ""TradeIn"" BOOLEAN NOT NULL,
    ""AdvertiserType"" TEXT NOT NULL,
    ""EstateNetArea"" INTEGER,
    ""EstateGrossArea"" INTEGER,
    ""EstateRoomCount"" TEXT,
    ""EstateBuildingAge"" TEXT,
    ""EstateTotalFloors"" INTEGER,
    ""EstateFloorLocation"" TEXT,
    ""HeatingType"" TEXT,
    ""EstateFurnished"" BOOLEAN,
    ""InSite"" BOOLEAN,
    ""HasBalcony"" BOOLEAN,
    ""HasElevator"" BOOLEAN,
    ""HasParking"" BOOLEAN,
    ""HasPool"" BOOLEAN,
    ""HasSecurity"" BOOLEAN,
    ""DuesAmount"" DECIMAL(18,2),
    ""DepositAmount"" DECIMAL(18,2),
    ""VehicleBrand"" TEXT,
    ""VehicleModel"" TEXT,
    ""VehicleYear"" INTEGER,
    ""VehicleFuelType"" TEXT,
    ""VehicleTransmission"" TEXT,
    ""VehicleKM"" INTEGER,
    ""VehicleBodyType"" TEXT,
    ""EngineCapacity"" INTEGER,
    ""EnginePower"" INTEGER,
    ""VehicleColor"" TEXT,
    ""VehiclePlate"" TEXT,
    ""UnderWarranty"" BOOLEAN,
    ""AccidentRecord"" TEXT,
    ""ProductBrand"" TEXT,
    ""ProductModel"" TEXT,
    ""ProductCondition"" TEXT,
    ""WarrantyPeriod"" TEXT,
    ""SerialNumber"" TEXT,
    ""UsageDuration"" TEXT,
    ""VideoUrl"" TEXT,
    ""CoverImageIndex"" INTEGER NOT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""IsApproved"" BOOLEAN NOT NULL,
    ""UserId"" TEXT,
    ""IsFeatured"" BOOLEAN NOT NULL,
    ""IsVitrin"" BOOLEAN NOT NULL,
    ""FeaturedExpiryDate"" TEXT,
    ""VitrinExpiryDate"" TEXT,
    ""FeaturedPackage"" TEXT,
    ""VitrinPackage"" TEXT,
    CONSTRAINT ""PK_Listings"" PRIMARY KEY (""Id"")
);

-- VisitorMessages (with IsArchived!)
CREATE TABLE ""VisitorMessages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""ListingId"" INTEGER NOT NULL,
    ""ConversationId"" TEXT NOT NULL,
    ""RecipientUserId"" TEXT,
    ""RecipientPhone"" TEXT,
    ""RecipientEmail"" TEXT,
    ""SenderUserId"" TEXT,
    ""SenderName"" TEXT NOT NULL,
    ""SenderEmail"" TEXT NOT NULL,
    ""SenderPhone"" TEXT,
    ""Subject"" TEXT NOT NULL,
    ""Message"" TEXT NOT NULL,
    ""CreatedAtUtc"" TEXT NOT NULL,
    ""IsArchived"" BOOLEAN NOT NULL DEFAULT FALSE,
    ""IsRead"" BOOLEAN NOT NULL,
    ""SenderRole"" TEXT NOT NULL,
    CONSTRAINT ""PK_VisitorMessages"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_VisitorMessages_Listings_ListingId"" FOREIGN KEY (""ListingId"") REFERENCES ""Listings"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""ListingMessages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""ListingId"" INTEGER NOT NULL,
    ""SenderUserId"" TEXT NOT NULL,
    ""ReceiverUserId"" TEXT NOT NULL,
    ""Body"" TEXT NOT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""ReadAt"" TEXT,
    CONSTRAINT ""PK_ListingMessages"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_ListingMessages_AspNetUsers_ReceiverUserId"" FOREIGN KEY (""ReceiverUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_ListingMessages_AspNetUsers_SenderUserId"" FOREIGN KEY (""SenderUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_ListingMessages_Listings_ListingId"" FOREIGN KEY (""ListingId"") REFERENCES ""Listings"" (""Id"") ON DELETE CASCADE
);

-- Other tables
CREATE TABLE ""ListingImages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""FilePath"" TEXT NOT NULL,
    ""ListingId"" INTEGER NOT NULL,
    ""UserId"" TEXT,
    CONSTRAINT ""PK_ListingImages"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_ListingImages_Listings_ListingId"" FOREIGN KEY (""ListingId"") REFERENCES ""Listings"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""PricingPackages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""Name"" TEXT NOT NULL,
    ""PackageType"" TEXT NOT NULL,
    ""Tier"" TEXT NOT NULL,
    ""Price"" DECIMAL(18,2) NOT NULL,
    ""Currency"" TEXT NOT NULL,
    ""DurationDays"" INTEGER NOT NULL,
    ""ListingsIncluded"" INTEGER NOT NULL,
    ""Description"" TEXT,
    ""IsActive"" BOOLEAN NOT NULL,
    ""DisplayOrder"" INTEGER NOT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    CONSTRAINT ""PK_PricingPackages"" PRIMARY KEY (""Id"")
);

CREATE TABLE ""UserPackages"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" TEXT NOT NULL,
    ""PackageId"" INTEGER NOT NULL,
    ""TotalPurchased"" INTEGER NOT NULL,
    ""UsedCount"" INTEGER NOT NULL,
    ""ExpiryDate"" TEXT,
    ""IsActive"" BOOLEAN NOT NULL,
    ""PurchasedAt"" TEXT NOT NULL,
    CONSTRAINT ""PK_UserPackages"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_UserPackages_PricingPackages_PackageId"" FOREIGN KEY (""PackageId"") REFERENCES ""PricingPackages"" (""Id""),
    CONSTRAINT ""FK_UserPackages_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""Payments"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" TEXT NOT NULL,
    ""PackageId"" INTEGER,
    ""PaymentMethod"" TEXT NOT NULL,
    ""PaymentStatus"" TEXT NOT NULL,
    ""Amount"" DECIMAL(18,2) NOT NULL,
    ""Currency"" TEXT NOT NULL,
    ""TransactionId"" TEXT,
    ""ExternalPaymentId"" TEXT,
    ""PaymentDetails"" TEXT,
    ""Note"" TEXT,
    ""CreatedAt"" TEXT NOT NULL,
    ""CompletedAt"" TEXT,
    CONSTRAINT ""PK_Payments"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_Payments_PricingPackages_PackageId"" FOREIGN KEY (""PackageId"") REFERENCES ""PricingPackages"" (""Id""),
    CONSTRAINT ""FK_Payments_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""ListingPromotions"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""ListingId"" INTEGER NOT NULL,
    ""UserId"" TEXT NOT NULL,
    ""PromotionType"" TEXT NOT NULL,
    ""PackageName"" TEXT NOT NULL,
    ""DurationDays"" INTEGER NOT NULL,
    ""StartedAt"" TEXT NOT NULL,
    ""ExpiresAt"" TEXT NOT NULL,
    ""IsActive"" BOOLEAN NOT NULL,
    ""PaymentId"" INTEGER,
    CONSTRAINT ""PK_ListingPromotions"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_ListingPromotions_Listings_ListingId"" FOREIGN KEY (""ListingId"") REFERENCES ""Listings"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""Reviews"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""ListingId"" INTEGER NOT NULL,
    ""UserId"" TEXT NOT NULL,
    ""UserName"" TEXT NOT NULL,
    ""Rating"" INTEGER NOT NULL,
    ""Comment"" TEXT NOT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    ""IsApproved"" BOOLEAN NOT NULL,
    ""ModeratedAt"" TEXT,
    ""ModeratedByUserId"" TEXT,
    ""ModerationNote"" TEXT,
    ""ModerationStatus"" INTEGER,
    CONSTRAINT ""PK_Reviews"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_Reviews_Listings_ListingId"" FOREIGN KEY (""ListingId"") REFERENCES ""Listings"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""UserFavorites"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" TEXT NOT NULL,
    ""ListingId"" INTEGER NOT NULL,
    ""CreatedAt"" TEXT NOT NULL,
    CONSTRAINT ""PK_UserFavorites"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_UserFavorites_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_UserFavorites_Listings_ListingId"" FOREIGN KEY (""ListingId"") REFERENCES ""Listings"" (""Id"") ON DELETE CASCADE
);

CREATE UNIQUE INDEX ""IX_UserFavorites_UserId_ListingId"" ON ""UserFavorites"" (""UserId"", ""ListingId"");

CREATE TABLE ""Documents"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" TEXT NOT NULL,
    ""DocumentType"" INTEGER NOT NULL,
    ""FileName"" TEXT NOT NULL,
    ""FilePath"" TEXT NOT NULL,
    ""UploadDate"" TEXT NOT NULL,
    CONSTRAINT ""PK_Documents"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_Documents_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE ""AdminAuditLogs"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ""ActorUserId"" TEXT NOT NULL,
    ""ActorEmail"" TEXT NOT NULL,
    ""Action"" TEXT NOT NULL,
    ""TargetType"" TEXT NOT NULL,
    ""TargetId"" TEXT,
    ""Details"" TEXT,
    ""IpAddress"" TEXT,
    ""UserAgent"" TEXT,
    ""CreatedAtUtc"" TEXT NOT NULL,
    CONSTRAINT ""PK_AdminAuditLogs"" PRIMARY KEY (""Id"")
);

-- Indexes
CREATE INDEX ""IX_ListingImages_ListingId"" ON ""ListingImages"" (""ListingId"");
CREATE INDEX ""IX_ListingPromotions_ListingId"" ON ""ListingPromotions"" (""ListingId"");
CREATE INDEX ""IX_Payments_PackageId"" ON ""Payments"" (""PackageId"");
CREATE INDEX ""IX_Payments_UserId"" ON ""Payments"" (""UserId"");
CREATE INDEX ""IX_Reviews_ListingId"" ON ""Reviews"" (""ListingId"");
CREATE INDEX ""IX_UserFavorites_ListingId"" ON ""UserFavorites"" (""ListingId"");
CREATE INDEX ""IX_UserPackages_PackageId"" ON ""UserPackages"" (""PackageId"");
CREATE INDEX ""IX_VisitorMessages_ListingId"" ON ""VisitorMessages"" (""ListingId"");
CREATE INDEX ""IX_ListingMessages_ListingId"" ON ""ListingMessages"" (""ListingId"");
CREATE INDEX ""IX_ListingMessages_ReceiverUserId"" ON ""ListingMessages"" (""ReceiverUserId"");
CREATE INDEX ""IX_ListingMessages_SenderUserId"" ON ""ListingMessages"" (""SenderUserId"");
";

using var cmd = new NpgsqlCommand(sql, conn);
await cmd.ExecuteNonQueryAsync();
Console.WriteLine("Tables created successfully!");

// Create migrations history table
using var histTableCmd = new NpgsqlCommand(
    "CREATE TABLE \"__EFMigrationsHistory\" (\"MigrationId\" TEXT NOT NULL, \"ProductVersion\" TEXT NOT NULL, CONSTRAINT \"PK___EFMigrationsHistory\" PRIMARY KEY (\"MigrationId\"))", 
    conn);
await histTableCmd.ExecuteNonQueryAsync();

// Insert migration history
using var histCmd = new NpgsqlCommand(
    "INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('20260529090000_PostgreSQLSchema', '8.0.0')", 
    conn);
await histCmd.ExecuteNonQueryAsync();
Console.WriteLine("Migration history recorded!");

conn.Close();